[workspace]
members = [
    "cryotherm",
]
resolver = "3"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[workspace.lints.rust]
unsafe_code = "deny"
unused_results = "deny"
missing_debug_implementations = "deny"
missing_docs = "warn"
unused_crate_dependencies = "warn"
unreachable_pub = "warn"
unused_qualifications = "warn"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"

[workspace.lints.clippy]
unwrap_used = "deny"
